### ISSUE TITLE
User Attestations

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-contracts#20]
To verify that a user of radicle's funding contracts is the same user as a user on the radicle-link level, we need some kind of proof that is verifiable by any client, given a connection to both Ethereum and the Radicle Link network.

The use-cases are the following:
* Given the maintainer of a radicle link project, find their Ethereum donation address.
* Given an Ethereum address, find out if it belongs to any user of radicle link.

Basically, we'd like any client (eg. upstream) to easily relate and link Ethereum addresses with radicle link (stable) identifiers.

The proposed method only requires state on Ethereum.

---

**Proposal**

To create the link between the two networks, the user creates an **attestation** on chain (Ethereum). This attestation is essentially a signature of the radicle link id, stored in the Ethereum state and associated with the user's Ethereum account, by means of the transaction author (`msg.sender` in solidity).

```solidity
// Mapping of all attestations.
mapping(address => Attestation) attestations;

struct Attestation {
  bytes32 id; // The radicle-link id (root hash)
  bytes64 signature; // signature using one of the device keys (certifiers) under the radicle identity
  bytes32 publicKey; // the public (device) key associated with the above signature
}
```

The signature is created off-chain like so:

```
signature = secretKey.sign(ethereumAccountId + radicleId)
```

And stored on chain, using the transaction author as the associated ethereum account. Eg.

```solidity
function attest(bytes32 id, bytes64 signature, bytes32 publicKey) {
  attestations[msg.sender] = Attestation { id, signature, publicKey };
}
```

To verify the attestation:

1. Get the latest set of public keys under the radicle link identity being verified.
2. Get the attestation from the Ethereum state. (Eg. using the radicle link id via the reverse index)
3. Verify that the public key in the attestation is one of the keys authorized to sign on behalf of the identity in (1)
4. Verify the attestation signature using the public key in the attestation, and a concatination of the radicle id with the ethereum account id. ie. `public_key.verify(attestation.signature, &[ethereum_account_id, attestation.id])`

---

If the device key used to attest is lost, a new attestation should be made. This way, the device key can be revoked with no problem.

Note also that with this method, the identity doc on radicle link doesn't need to be updated when an attestation is made.

**Comment by cloudhead** [comment]
Would like a review of the concept from @kim @xla @CodeSandwich at least before starting implementation.

**Comment by cloudhead** [comment]
> The reverse index might present a problem: since writing to it doesn't require a valid attestation thinking. Potentially, we'll have to drop it, and include this information elsewhere, or on-chain but in a different form. One of the unfortunate downsides of switching to Ethereum that we didn't talk about much is that radicle link signatures cannot be verified on-chain.

Some other potential directions:
* Don't create the reverse lookup during the attestation. Create it later, as a `rel = <ethereum-address>` in the radicle link id document.
* Store multiple ethereum addresses per radicle id on chain. Clients can then check all of them.
* Create an ECDSA key during identity creation in radicle-link, and use that key to sign. This means it can be verified on-chain and the reverse-index cannot be vandalized.
* Verify the EdDSA signature on-chain. Same as above, except this will be expensive in gas costs.

**Comment by geigerzaehler** [comment]
> Don't create the reverse lookup during the attestation. Create it later, as a `rel = <ethereum-address>` in the radicle link id document. This has the disadvantage of being non-atomic. ie. it's possible for the two worlds to diverge.

The problem of divergent state is also present in the initial proposal: 

>     1. Get the latest set of public keys under the radicle link identity being verified.

We rely on the public key being linked to the identity. So if the key is revoked or a new one is added and used for the attestation the state on Ethereum might differ from the view that is available to a verifier. I don’t think this is an issue we can eliminate.

This is why I prefer including the Ethereum address in the identity document. This could also simplify what we store on chain. It should be sufficient to just store the Radicle Link ID without signing it. The signature is implicit in the document that links to the Ethereum address

**Comment by cloudhead** [comment]
Yeah, I think the solution involves storing a reverse-pointer in the identity document. This seems like the most straightforward way.

The thing I'm still unsure of, is whether to store a signature on chain, or just the radicle id. Just storing the id means that I never really have to have both keys at the same time, ie. I can:

1. Create the on-chain attestation without the radicle link key.
2. Then create the radicle link attestation without the on-chain key (eg. I lost it in the meantime).

I'm not sure what this means but it makes me ponder.

> We rely on the public key being linked to the identity. So if the key is revoked or a new one is added and used for the attestation the state on Ethereum might differ from the view that is available to a verifier. I don’t think this is an issue we can eliminate.

Hmm, but revocation can be anchored on chain for eg., and then you could establish a strict ordering between events?

I kind of like that the transaction contains the complete proof of ownership, with a provable timestamp (the block time). This will allow us to know when a revocation happens, which came first. If the attestation is a two-step process, there's no clear point in time at which we can say "these keys belong to the same user". Does that make sense? :thinking:

**Comment by geigerzaehler** [comment]
> 1. Create the on-chain attestation without the radicle link key.

Does this work? Don’t you need the radicle link key to create the signature of the attestation?



> 2. Then create the radicle link attestation without the on-chain key (eg. I lost it in the meantime).

We don’t need to know the secret key for the Ethereum address to create the attestation on Radicle Link, right? It’s just a pointer to the Ethereum address. In any case, I don’t think it makes sense to create it if the on-chain key is lost.





> > We rely on the public key being linked to the identity. So if the key is revoked or a new one is added and used for the attestation the state on Ethereum might differ from the view that is available to a verifier. I don’t think this is an issue we can eliminate.
>
> Hmm, but revocation can be anchored on chain for eg., and then you could establish a strict ordering between events?

In addition to making the protocol more complex, I doubt this works. The chicken-and-egg problem is deciding who can revoke a key. It can only be someone controlling the identity—but then how do you validate that on chain.

In any case we would still need to deal with adding a key: The verifier may see an attestation with a specific public key. However that key was only added to the identity recently and the verifier is unable to get that data because the identity update is not being replicated at the moment.

**Comment by kim** [comment]
It is correct that we need the Ethereum address in the `link` document, otherwise one can only find the `link` identity if the Ethereum identity is already known.

 >  It should be sufficient to just store the Radicle Link ID without signing it

This is **not** sufficient. I've expanded on this [here](https://github.com/radicle-dev/radicle-registry/pull/589#issuecomment-674505836) and [here](https://github.com/radicle-dev/radicle-registry/pull/589#issuecomment-680834421). 

The short version of the argument is that the usefulness of this feature is rather limited if I need _both_ sides to verify that the attester was in possession of both keys at time X. Since both sides are verifiable chains, however, later revocations don't invalidate the attestation.

It is possible to put the proof burden entirely on the `link` side, i.e. not only include the Ethereum address, but also a signature made by the transaction key. The result is that I can not talk about validity of that piece of metadata (the `link` identifier) by looking only at the chain -- anyone could have included it, and perhaps its even associated with multiple addresses. _But_, I can talk about validity of that Ethereum address without looking at the chain.

If, conversely, the `link` identifier stored on-chain is also signed, only the holder of that `link` key can make the attestation, and I don't need to look at the `link` side to verify that.

So it boils down to the question what do we want from this feature? 

If I want to send some money to that rockstar developer, I might not actually want to follow them on `link` -- all I got is a random-looking URN from the "Money Zu Verschenken" channel on telegram, and I want to make sure I send the ETH to the right address.

I find it harder to come up with a compelling use case for the other way round. My feeling is that there might be some in the context of "organisations" or "DAOs", or when considering off-chain services: what keybase does is to submit the merkle root of their _entire_ userbase to Stellar. As an example, consider a service which provides replication for some community within `link` (or the entire network) -- to prove that they're not altering anything, they could do the same.

**Comment by kim** [comment]
@geigerzaehler It will never be possible to revoke a `link` key on-chain -- attestation is only about establishing a relationship between both systems.

**Comment by cloudhead** [comment]
> The short version of the argument is that the usefulness of this feature is rather limited if I need both sides to verify that the attester was in possession of both keys at time X. Since both sides are verifiable chains, however, later revocations don't invalidate the attestation.

Exactly!

> If I want to send some money to that rockstar developer, I might not actually want to follow them on link -- all I got is a random-looking URN from the "Money Zu Verschenken" channel on telegram, and I want to make sure I send the ETH to the right address.

Can we do this safely though? Can't someone trick you by signing the rockstar's id with their key? You'll have no way to know that the public key used doesn't belong to the rockstar? eg. `attackerKey.sign(rockstar.id ++ attacker.address)` -- wouldn't the only way to invalidate this be to have an up-to-date sigchain for `rockstar`?

**Comment by geigerzaehler** [comment]
> Can't someone trick you by signing the rockstar's id with their key? You'll have no way to know that the public key used doesn't belong to the rockstar?

I think you’re right. For you to trust an attestation you need to know that the public key that is stored as part of the attestation is controlled by the Radicle Link identity. This means you need access to the Radicle Link information after all.

**Comment by CodeSandwich** [comment]
I can't recall, did we ever consider deriving an Ethereum private key and address from link private key? It's probably a stupid idea due to link's volatility, but it would remove the need for attestation and break the attestation symmetry.

**Comment by cloudhead** [comment]
Some additional points discussed offline:

* Compared to Keybase, one big difference is that Keybase is trying to attest ownership of a **public key** (by eg. a Twitter user), whereas we are primarily trying to attest ownership of a **radicle id**. Since you cannot sign with a radicle id, it's hard to establish that direct relation without having the `radicle_id -> [public_key]` mapping.
* There *may be* some cases where proving the link between a **public key** and an **ethereum address** may actually be useful (without being able to verify the **radicle id**). This usecase *would* be covered partially by using an on-chain signature, but would require *all* public (device) keys to be attested on-chain. Such a use-case could be: linking a **signed artifact** (eg. an issue, pr, code ref) with an **ethereum address**. This is a benefit that we don't get by simply including the id on chain.
* I'm still trying to think of practical attacks on the simple two-way link with no signatures.

**Comment by cloudhead** [comment]
Okay, so here's a concrete security flaw of the simple two-way link model:

1. User creates two way link between eth address `0x123` and rad id `@abcdef`.
2. Attacker steals keys to `0x123`, creates new attestation pointing to `@attacker`.
3. The attestation remains valid until `@abcdef` changes the identity doc to point to a new ethereum address.

If this was using an on-chain signature, the attacker would not be able to compromise the attestation by stealing only one key. Having attestations be immutable would be a defense against this, but now if you lose your link id, you also need a new ethereum address.

**Comment by geigerzaehler** [comment]
> Okay, so here's a concrete security flaw of the simple two-way link model:

If I’m not mistaken this is also a problem if we have signatures on-chain

1. User creates two way link between eth address `0x123` and rad id `@abcdef`.
2. Attacker steals keys to `0x123`
3. Attacker uses private key of `@attacker` to sign `0x123 ++ @attacker`
4. Attacker uses private key of `0x123` to create an attestation.

**Comment by cloudhead** [comment]
You're right, because there is no way for an observer to know whether `@abcdef` just lost their radicle-link id and is switching their ethereum address to a new radicle link id. :thinking:

**Comment by cloudhead** [comment]
In fact, the attack I described makes no sense now that I think about it. :laughing:

**Comment by kim** [comment]
I think that what we can expect from this feature is basically the same as what keychain does, and should work essentially the same way: you need to have _a priori_ reason to believe that either this address or that public key belongs to a specific person (that is, you _trust_ it to some degree). By means of cryptographic proofs you can _extend_ your trust to the respective other system, which may also increase your confidence overall that these identities are indeed associated with a real person.

In that sense, it might be worth considering to support other keybase-style proofs in the future -- GH, Twitter, etc. Those are different, however, in the sense that we cannot obtain a proof of ownership from them -- that's why keybase doesn't require any external keys to sign the claim on the keybase sigchain. There is also the consideration that on-chain attestations cost money, so you don't want to do this for every internet presence of yours. Iow, if we do this, it should be on the `link` side.

So, again, the fact that I'm anchoring my `link` identity on-chain **does not** increase its security, only its trustworthiness.

The attack described above is actually _prevented_ by requiring the attestation to be signed by a `link` key: what should get submitted is `SIG(root_hash || revision)`, where `revision` contains the claim of owning the address. An attacker therefore must be able to gain control of a majority of `link` keys **and** the transaction key in order to take over that identity. Of course, the owner of the transaction key could _revoke_ the attestation, and create a new one pointing to a completely different identity -- however, the `root_hash` will change in this case, so whether I'm willing to accept this as legit is a matter of accepting the chain as the ultimate source of truth. Note that supporting keybase-style proofs on more external services would make this kind of unfriendly takeover harder.

**Comment by cloudhead** [comment]
Ok this makes sense to me. Going to go ahead with an implementation, and we can continue discussion in the PR.
